### PR TITLE
Update to Typescript 3.8

### LINKED ISSUE #65: Update to Typescript 3.8
### Observed behavior
Updating the typescript and typedoc versions according to the snippet below without using stricter linting makes it possible to use the current typescript version with a minimum amount of errors.  
```
"typedoc": "~0.16.9",
"typescript": "~3.8.1-rc",
```

### Expected behavior
Updating the dependencies in the _package.json_ and adding the following line of code in _tsconfig.json_ (as well as fixing appearing type errors) should be sufficient for the usage of Typescript 3.8 as a first step.
```
"downlevelIteration": true, // required as long as target is `es5`
```

### PR DESCRIPTION
**Pull request by dvvanessastoiber**
Closes #65 

### Summary
* update to typescript `v3.8` and typedoc `v0.16.9`
* switch branches in _package.json_
* update `tslib`
* set `downlevelIteration": true` in _tsconfig.json_

### CODE REVIEW

**Comment by thinkh** [comment]
I don't know if it caused by this TypeScript change, but I get an error when performing the following actions:

1. Open localhost
2. Jump to year 1901 (or any other year)
3. Switch x-axis to _Child Mortality_ (or any other attribute)

gapminder-localhost

Error in the developer console is pointing to `updateTimeLine` in _gapminder.ts_:

```
Error: <path> attribute transform: Expected number, "translate(NaN,14)".
attrConstant @ d3.js:663
(anonymous) @ d3.js:962
d3_selection_each @ d3.js:968
d3_selectionPrototype.each @ d3.js:961
d3_selectionPrototype.attr @ d3.js:652
updateTimeLine @ gapminder.ts:828
update @ gapminder.ts:631
(anonymous) @ gapminder.ts:916
Promise.then (async)
setAttributeImpl @ gapminder.ts:905
(anonymous) @ gapminder.ts:28
then @ promise.ts:7
setAttributeImpl @ gapminder.ts:24
execute @ ActionNode.ts:191
run @ ProvenanceGraph.ts:670
(anonymous) @ ProvenanceGraph.ts:467
inOrder @ ProvenanceGraph.ts:585
push @ ProvenanceGraph.ts:462
setAttribute @ gapminder.ts:948
(anonymous) @ gapminder.ts:303
(anonymous) @ d3.js:1120
ListPicker._handleMouseUp
```

In the online demo at https://gapminder.caleydoapp.org/ (Version: 2.0.0) everything is working.

gapminder-caleydoapp

**Review by thinkh — CHANGES_REQUESTED** [review]
See previous error report.

**Comment by thinkh** [comment]
I checked the same steps with the current develop branch (Typescript 2.8.1) and get the same error. Hence, the error must have been introduced earlier than this PR.

[Comparing the current develop branch with the master](https://github.com/Caleydo/gapminder/compare/develop), shows not much releated activity for this repository. So problem must be in a different repo or some dependencies.

@dvvanessastoiber Could you please test the gapminder workspace with develop again on your machine?

**Comment by dvvanessastoiber** [comment]
> I checked the same steps with the current develop branch (Typescript 2.8.1) and get the same error. Hence, the error must have been introduced earlier than this PR.
> 
> [Comparing the current develop branch with the master](https://github.com/Caleydo/gapminder/compare/develop), shows not much releated activity for this repository. So problem must be in a different repo or some dependencies.
> 
> @dvvanessastoiber Could you please test the gapminder workspace with develop again on your machine?

@thinkh Thanks for the error report! I will test in on my machine. Could this issue be related with [this PR](https://github.com/phovea/phovea_server/pull/113) and the underlying issue? A NaN value seems to be involved.

**Comment by dvvanessastoiber** [comment]
When I test it locally on my machine with all branches set to `develop`, everything seems to work fine. See Screenshot:
Screenshot_1

and video:

Peek 2020-02-28 07-30

**Comment by ghost** [comment]
see https://github.com/novus/nvd3/issues/721

**Review by thinkh — APPROVED** [review]
I tested it again today and it works with both branches (develop and typescript_3.8)!

Before every test I ran `rm -rf node_modules && rm -rf package-lock.json` and installed the node_modules from scratch.

**Pull request merged**
